{% set name = "pybids" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybids-{{ version }}.tar.gz
  sha256: e000335eae5b7749ea9621adca4a17309fb9a4bb67a3f4231a70155267875a50

build:
  entry_points:
    - pybids=bids.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=30.3.0,!=61.0.0
    - versioneer
    - tomli
  run:
    - python >=3.8
    - numpy >=1.19
    - scipy >=1.5
    - nibabel >=3.0
    - pandas >=0.25.2
    - formulaic >=0.2.4, <0.6
    - sqlalchemy >=1.3.16
    - bids-validator >=1.11
    - num2words >=0.5.5
    - click >=8.0
    - universal_pathlib >=0.2.2

test:
  imports:
    - bids
  commands:
    - pip check
    - pybids --help
  requires:
    - pip

about:
  home: http://github.com/bids-standard/pybids
  summary: 'bids: interface with datasets conforming to BIDS'
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - adelavega
    - effigies
    - sarthakpati
