{% set name = "pybids" %}
{% set version = "0.20.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybids-{{ version }}.tar.gz
  sha256: a68b577426942e50e6ac37e011463361d00a378d19b75df817619450357ebbb6

build:
  entry_points:
    - pybids=bids.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - versioneer
    - tomli
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - scipy >=1.9
    - nibabel >=4.0
    - pandas >=1.5
    - formulaic >=0.3
    - sqlalchemy >=1.4.31
    - bids-validator >=1.14.7
    - num2words >=0.5.10
    - click >=8.0
    - universal_pathlib >=0.2.2
    - frozendict >=2.3

test:
  imports:
    - bids
  commands:
    - pip check
    - pybids --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/bids-standard/pybids
  summary: 'bids: interface with datasets conforming to BIDS'
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - adelavega
    - effigies
    - sarthakpati
